
out={
            "names":i['PlaceName'],
            "categories":i['PlaceType'],
            "prize_ranges":i['PriceRange'],
            "ratings":i['Rating'],
            "review_n":i['Rating_n'],
            "addresses":i['Address'],
            "Neighborhoods":i['Neighborhood'],
            "states":""),
            "cities":(i['Address']),.split(",")[-2],
            "countries":i['Country'],
            "latitudes":i['Latitude'],
            "longitudes":i['Longitude'],
            "zipcodes":i['Zipcode'],
            "phones":i['PhoneNumber'],
            "URL":d['Business'],
            "instagrams":d['instagram'],
            "facebooks":d['facebook'],
            "twitters":d['twitter'],
            "tiktoks":d['tiktok'],
            "emails":str(d['email'],.replace("'","").replace("[","").replace("]",""))
            print(d)